// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Szkolenie3API.Data;

#nullable disable

namespace Szkolenie3API.Migrations
{
    [DbContext(typeof(ProjektDbContext))]
    [Migration("20230619151213_DbSeeded")]
    partial class DbSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Szkolenie3API.Data.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Maine Coon",
                            Color = "Tabby",
                            Description = "Maine Coons are large, long-haired cats known for their friendly and sociable nature. They are often referred to as the 'gentle giants' of the cat world.",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Siamese",
                            Color = "Seal Point",
                            Description = "Siamese cats are known for their striking blue eyes and distinctive color points on their ears, face, paws, and tail. They are highly vocal and social cats.",
                            Weight = 8.0
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Persian",
                            Color = "White",
                            Description = "Persian cats have long, luxurious coats and a distinctive flat face. They are calm and gentle companions, often enjoying a relaxed lifestyle.",
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Abyssinian",
                            Color = "Ruddy",
                            Description = "Abyssinians are active and playful cats with short, ticked coats. They are known for their curious and outgoing personalities.",
                            Weight = 6.0
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Scottish Fold",
                            Color = "Blue",
                            Description = "Scottish Folds have unique folded ears that give them a distinctive appearance. They are known for their sweet and gentle temperament.",
                            Weight = 7.0
                        });
                });

            modelBuilder.Entity("Szkolenie3API.Data.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Akita",
                            Color = "Ginger",
                            Description = "Akitas are quiet, fastidious dogs. Wary of strangers and often intolerant of other animals, Akitas will gladly share their silly, affectionate side with family and friends.",
                            Weight = 30.5
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Labrador Retriever",
                            Color = "Yellow",
                            Description = "Labrador Retrievers are friendly, outgoing, and eager to please. They are intelligent and versatile, excelling in various roles, including search and rescue, therapy work, and assistance to people with disabilities.",
                            Weight = 25.0
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Bulldog",
                            Color = "White",
                            Description = "Bulldogs are known for their sturdy build and distinctive pushed-in nose. Despite their tough appearance, they are generally gentle and great with children.",
                            Weight = 25.0
                        },
                        new
                        {
                            Id = 4,
                            Breed = "German Shepherd",
                            Color = "Tan and Black",
                            Description = "German Shepherds are highly intelligent and versatile dogs. They are often used as working dogs in roles such as search and rescue, police, and service dogs.",
                            Weight = 75.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
